### ISSUE TITLE
行间距与模板不一致

### ISSUE THREAD

**Issue by zdlspace0528** [fylimas/nsfc#10]
图片是我编译生成的PDF截图，（一）立项依据前后的间距不一致，而模板中前后间距是一样的，建议调整一下。
<img width="758" alt="截屏2024-02-23 21 40 07" src="https://github.com/fylimas/nsfc/assets/75175622/2623c414-53d9-414d-8f62-371e9b196d0d">

**Comment by fylimas** [comment]
用\vspace{3pt}就行。谢谢，已修改。
