### ISSUE TITLE
青基图表示例中图名不对

### ISSUE THREAD

**Issue by hitiler** [fylimas/nsfc#13]
figures文件夹中的图名和青基文件中的图名对不上导致编译错误

**Comment by wgqhandsome** [comment]
解决了吗？

**Comment by fylimas** [comment]
很好解决，编译一下，修改一下图片名字就OK了

**Comment by wgqhandsome** [comment]
> 很好解决，编译一下，修改一下图片名字就OK了

二维码已过期，你能邀请我一下吗？

**Comment by fylimas** [comment]
> > 很好解决，编译一下，修改一下图片名字就OK了
> 
> 二维码已过期，你能邀请我一下吗？

没问题，群二维码时间太短了，搜索fylimas加我微信就行
