### ISSUE TITLE
进群二维码过期

### ISSUE THREAD

**Issue by huangwb8** [fylimas/nsfc#8]
之前是学习另外两个项目：

- [Ruzim/NSFC-application-template-latex](https://github.com/Ruzim/NSFC-application-template-latex)
- [Readon/NSFC-application-template-latex](https://github.com/Readon/NSFC-application-template-latex)

因为我最近也有在维护自己的模板： 

+ [huangwb8/ChineseResearchLaTeX](https://github.com/huangwb8/ChineseResearchLaTeX)

发现您这边有个群，想进去交流学习一下。不过二维码已经过期了。

是否方便再发一个码？谢谢！

**Comment by fylimas** [comment]
谢谢提醒！现在更新为新的二维码啦
